// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/leeeeeoy/go_study/ent/board"
	"github.com/leeeeeoy/go_study/ent/boardlike"
	"github.com/leeeeeoy/go_study/ent/user"
)

// BoardLikeCreate is the builder for creating a BoardLike entity.
type BoardLikeCreate struct {
	config
	mutation *BoardLikeMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (blc *BoardLikeCreate) SetUserID(i int) *BoardLikeCreate {
	blc.mutation.SetUserID(i)
	return blc
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (blc *BoardLikeCreate) SetNillableUserID(i *int) *BoardLikeCreate {
	if i != nil {
		blc.SetUserID(*i)
	}
	return blc
}

// SetBoardID sets the "board_id" field.
func (blc *BoardLikeCreate) SetBoardID(i int) *BoardLikeCreate {
	blc.mutation.SetBoardID(i)
	return blc
}

// SetNillableBoardID sets the "board_id" field if the given value is not nil.
func (blc *BoardLikeCreate) SetNillableBoardID(i *int) *BoardLikeCreate {
	if i != nil {
		blc.SetBoardID(*i)
	}
	return blc
}

// SetCreatedAt sets the "created_at" field.
func (blc *BoardLikeCreate) SetCreatedAt(t time.Time) *BoardLikeCreate {
	blc.mutation.SetCreatedAt(t)
	return blc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (blc *BoardLikeCreate) SetNillableCreatedAt(t *time.Time) *BoardLikeCreate {
	if t != nil {
		blc.SetCreatedAt(*t)
	}
	return blc
}

// SetUser sets the "user" edge to the User entity.
func (blc *BoardLikeCreate) SetUser(u *User) *BoardLikeCreate {
	return blc.SetUserID(u.ID)
}

// SetBoard sets the "board" edge to the Board entity.
func (blc *BoardLikeCreate) SetBoard(b *Board) *BoardLikeCreate {
	return blc.SetBoardID(b.ID)
}

// Mutation returns the BoardLikeMutation object of the builder.
func (blc *BoardLikeCreate) Mutation() *BoardLikeMutation {
	return blc.mutation
}

// Save creates the BoardLike in the database.
func (blc *BoardLikeCreate) Save(ctx context.Context) (*BoardLike, error) {
	blc.defaults()
	return withHooks(ctx, blc.sqlSave, blc.mutation, blc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (blc *BoardLikeCreate) SaveX(ctx context.Context) *BoardLike {
	v, err := blc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (blc *BoardLikeCreate) Exec(ctx context.Context) error {
	_, err := blc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (blc *BoardLikeCreate) ExecX(ctx context.Context) {
	if err := blc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (blc *BoardLikeCreate) defaults() {
	if _, ok := blc.mutation.CreatedAt(); !ok {
		v := boardlike.DefaultCreatedAt()
		blc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (blc *BoardLikeCreate) check() error {
	if _, ok := blc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BoardLike.created_at"`)}
	}
	return nil
}

func (blc *BoardLikeCreate) sqlSave(ctx context.Context) (*BoardLike, error) {
	if err := blc.check(); err != nil {
		return nil, err
	}
	_node, _spec := blc.createSpec()
	if err := sqlgraph.CreateNode(ctx, blc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	blc.mutation.id = &_node.ID
	blc.mutation.done = true
	return _node, nil
}

func (blc *BoardLikeCreate) createSpec() (*BoardLike, *sqlgraph.CreateSpec) {
	var (
		_node = &BoardLike{config: blc.config}
		_spec = sqlgraph.NewCreateSpec(boardlike.Table, sqlgraph.NewFieldSpec(boardlike.FieldID, field.TypeInt))
	)
	if value, ok := blc.mutation.CreatedAt(); ok {
		_spec.SetField(boardlike.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := blc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   boardlike.UserTable,
			Columns: []string{boardlike.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := blc.mutation.BoardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   boardlike.BoardTable,
			Columns: []string{boardlike.BoardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(board.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BoardID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BoardLikeCreateBulk is the builder for creating many BoardLike entities in bulk.
type BoardLikeCreateBulk struct {
	config
	builders []*BoardLikeCreate
}

// Save creates the BoardLike entities in the database.
func (blcb *BoardLikeCreateBulk) Save(ctx context.Context) ([]*BoardLike, error) {
	specs := make([]*sqlgraph.CreateSpec, len(blcb.builders))
	nodes := make([]*BoardLike, len(blcb.builders))
	mutators := make([]Mutator, len(blcb.builders))
	for i := range blcb.builders {
		func(i int, root context.Context) {
			builder := blcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BoardLikeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, blcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, blcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, blcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (blcb *BoardLikeCreateBulk) SaveX(ctx context.Context) []*BoardLike {
	v, err := blcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (blcb *BoardLikeCreateBulk) Exec(ctx context.Context) error {
	_, err := blcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (blcb *BoardLikeCreateBulk) ExecX(ctx context.Context) {
	if err := blcb.Exec(ctx); err != nil {
		panic(err)
	}
}
