// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/leeeeeoy/go_study/ent/comment"
	"github.com/leeeeeoy/go_study/ent/commentreport"
	"github.com/leeeeeoy/go_study/ent/predicate"
	"github.com/leeeeeoy/go_study/ent/reporttype"
	"github.com/leeeeeoy/go_study/ent/user"
)

// CommentReportQuery is the builder for querying CommentReport entities.
type CommentReportQuery struct {
	config
	ctx            *QueryContext
	order          []commentreport.OrderOption
	inters         []Interceptor
	predicates     []predicate.CommentReport
	withUser       *UserQuery
	withComment    *CommentQuery
	withReportType *ReportTypeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CommentReportQuery builder.
func (crq *CommentReportQuery) Where(ps ...predicate.CommentReport) *CommentReportQuery {
	crq.predicates = append(crq.predicates, ps...)
	return crq
}

// Limit the number of records to be returned by this query.
func (crq *CommentReportQuery) Limit(limit int) *CommentReportQuery {
	crq.ctx.Limit = &limit
	return crq
}

// Offset to start from.
func (crq *CommentReportQuery) Offset(offset int) *CommentReportQuery {
	crq.ctx.Offset = &offset
	return crq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (crq *CommentReportQuery) Unique(unique bool) *CommentReportQuery {
	crq.ctx.Unique = &unique
	return crq
}

// Order specifies how the records should be ordered.
func (crq *CommentReportQuery) Order(o ...commentreport.OrderOption) *CommentReportQuery {
	crq.order = append(crq.order, o...)
	return crq
}

// QueryUser chains the current query on the "user" edge.
func (crq *CommentReportQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: crq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := crq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := crq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commentreport.Table, commentreport.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, commentreport.UserTable, commentreport.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(crq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryComment chains the current query on the "comment" edge.
func (crq *CommentReportQuery) QueryComment() *CommentQuery {
	query := (&CommentClient{config: crq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := crq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := crq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commentreport.Table, commentreport.FieldID, selector),
			sqlgraph.To(comment.Table, comment.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, commentreport.CommentTable, commentreport.CommentColumn),
		)
		fromU = sqlgraph.SetNeighbors(crq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryReportType chains the current query on the "report_type" edge.
func (crq *CommentReportQuery) QueryReportType() *ReportTypeQuery {
	query := (&ReportTypeClient{config: crq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := crq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := crq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commentreport.Table, commentreport.FieldID, selector),
			sqlgraph.To(reporttype.Table, reporttype.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, commentreport.ReportTypeTable, commentreport.ReportTypeColumn),
		)
		fromU = sqlgraph.SetNeighbors(crq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CommentReport entity from the query.
// Returns a *NotFoundError when no CommentReport was found.
func (crq *CommentReportQuery) First(ctx context.Context) (*CommentReport, error) {
	nodes, err := crq.Limit(1).All(setContextOp(ctx, crq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{commentreport.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (crq *CommentReportQuery) FirstX(ctx context.Context) *CommentReport {
	node, err := crq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CommentReport ID from the query.
// Returns a *NotFoundError when no CommentReport ID was found.
func (crq *CommentReportQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = crq.Limit(1).IDs(setContextOp(ctx, crq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{commentreport.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (crq *CommentReportQuery) FirstIDX(ctx context.Context) int {
	id, err := crq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CommentReport entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CommentReport entity is found.
// Returns a *NotFoundError when no CommentReport entities are found.
func (crq *CommentReportQuery) Only(ctx context.Context) (*CommentReport, error) {
	nodes, err := crq.Limit(2).All(setContextOp(ctx, crq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{commentreport.Label}
	default:
		return nil, &NotSingularError{commentreport.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (crq *CommentReportQuery) OnlyX(ctx context.Context) *CommentReport {
	node, err := crq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CommentReport ID in the query.
// Returns a *NotSingularError when more than one CommentReport ID is found.
// Returns a *NotFoundError when no entities are found.
func (crq *CommentReportQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = crq.Limit(2).IDs(setContextOp(ctx, crq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{commentreport.Label}
	default:
		err = &NotSingularError{commentreport.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (crq *CommentReportQuery) OnlyIDX(ctx context.Context) int {
	id, err := crq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CommentReports.
func (crq *CommentReportQuery) All(ctx context.Context) ([]*CommentReport, error) {
	ctx = setContextOp(ctx, crq.ctx, "All")
	if err := crq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CommentReport, *CommentReportQuery]()
	return withInterceptors[[]*CommentReport](ctx, crq, qr, crq.inters)
}

// AllX is like All, but panics if an error occurs.
func (crq *CommentReportQuery) AllX(ctx context.Context) []*CommentReport {
	nodes, err := crq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CommentReport IDs.
func (crq *CommentReportQuery) IDs(ctx context.Context) (ids []int, err error) {
	if crq.ctx.Unique == nil && crq.path != nil {
		crq.Unique(true)
	}
	ctx = setContextOp(ctx, crq.ctx, "IDs")
	if err = crq.Select(commentreport.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (crq *CommentReportQuery) IDsX(ctx context.Context) []int {
	ids, err := crq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (crq *CommentReportQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, crq.ctx, "Count")
	if err := crq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, crq, querierCount[*CommentReportQuery](), crq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (crq *CommentReportQuery) CountX(ctx context.Context) int {
	count, err := crq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (crq *CommentReportQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, crq.ctx, "Exist")
	switch _, err := crq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (crq *CommentReportQuery) ExistX(ctx context.Context) bool {
	exist, err := crq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CommentReportQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (crq *CommentReportQuery) Clone() *CommentReportQuery {
	if crq == nil {
		return nil
	}
	return &CommentReportQuery{
		config:         crq.config,
		ctx:            crq.ctx.Clone(),
		order:          append([]commentreport.OrderOption{}, crq.order...),
		inters:         append([]Interceptor{}, crq.inters...),
		predicates:     append([]predicate.CommentReport{}, crq.predicates...),
		withUser:       crq.withUser.Clone(),
		withComment:    crq.withComment.Clone(),
		withReportType: crq.withReportType.Clone(),
		// clone intermediate query.
		sql:  crq.sql.Clone(),
		path: crq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (crq *CommentReportQuery) WithUser(opts ...func(*UserQuery)) *CommentReportQuery {
	query := (&UserClient{config: crq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	crq.withUser = query
	return crq
}

// WithComment tells the query-builder to eager-load the nodes that are connected to
// the "comment" edge. The optional arguments are used to configure the query builder of the edge.
func (crq *CommentReportQuery) WithComment(opts ...func(*CommentQuery)) *CommentReportQuery {
	query := (&CommentClient{config: crq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	crq.withComment = query
	return crq
}

// WithReportType tells the query-builder to eager-load the nodes that are connected to
// the "report_type" edge. The optional arguments are used to configure the query builder of the edge.
func (crq *CommentReportQuery) WithReportType(opts ...func(*ReportTypeQuery)) *CommentReportQuery {
	query := (&ReportTypeClient{config: crq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	crq.withReportType = query
	return crq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CommentID int `json:"comment_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CommentReport.Query().
//		GroupBy(commentreport.FieldCommentID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (crq *CommentReportQuery) GroupBy(field string, fields ...string) *CommentReportGroupBy {
	crq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CommentReportGroupBy{build: crq}
	grbuild.flds = &crq.ctx.Fields
	grbuild.label = commentreport.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CommentID int `json:"comment_id,omitempty"`
//	}
//
//	client.CommentReport.Query().
//		Select(commentreport.FieldCommentID).
//		Scan(ctx, &v)
func (crq *CommentReportQuery) Select(fields ...string) *CommentReportSelect {
	crq.ctx.Fields = append(crq.ctx.Fields, fields...)
	sbuild := &CommentReportSelect{CommentReportQuery: crq}
	sbuild.label = commentreport.Label
	sbuild.flds, sbuild.scan = &crq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CommentReportSelect configured with the given aggregations.
func (crq *CommentReportQuery) Aggregate(fns ...AggregateFunc) *CommentReportSelect {
	return crq.Select().Aggregate(fns...)
}

func (crq *CommentReportQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range crq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, crq); err != nil {
				return err
			}
		}
	}
	for _, f := range crq.ctx.Fields {
		if !commentreport.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if crq.path != nil {
		prev, err := crq.path(ctx)
		if err != nil {
			return err
		}
		crq.sql = prev
	}
	return nil
}

func (crq *CommentReportQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CommentReport, error) {
	var (
		nodes       = []*CommentReport{}
		_spec       = crq.querySpec()
		loadedTypes = [3]bool{
			crq.withUser != nil,
			crq.withComment != nil,
			crq.withReportType != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CommentReport).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CommentReport{config: crq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, crq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := crq.withUser; query != nil {
		if err := crq.loadUser(ctx, query, nodes, nil,
			func(n *CommentReport, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := crq.withComment; query != nil {
		if err := crq.loadComment(ctx, query, nodes, nil,
			func(n *CommentReport, e *Comment) { n.Edges.Comment = e }); err != nil {
			return nil, err
		}
	}
	if query := crq.withReportType; query != nil {
		if err := crq.loadReportType(ctx, query, nodes, nil,
			func(n *CommentReport, e *ReportType) { n.Edges.ReportType = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (crq *CommentReportQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*CommentReport, init func(*CommentReport), assign func(*CommentReport, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CommentReport)
	for i := range nodes {
		fk := nodes[i].ReporterID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "reporter_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (crq *CommentReportQuery) loadComment(ctx context.Context, query *CommentQuery, nodes []*CommentReport, init func(*CommentReport), assign func(*CommentReport, *Comment)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CommentReport)
	for i := range nodes {
		fk := nodes[i].CommentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(comment.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "comment_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (crq *CommentReportQuery) loadReportType(ctx context.Context, query *ReportTypeQuery, nodes []*CommentReport, init func(*CommentReport), assign func(*CommentReport, *ReportType)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CommentReport)
	for i := range nodes {
		fk := nodes[i].ReportTypeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(reporttype.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "report_type_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (crq *CommentReportQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := crq.querySpec()
	_spec.Node.Columns = crq.ctx.Fields
	if len(crq.ctx.Fields) > 0 {
		_spec.Unique = crq.ctx.Unique != nil && *crq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, crq.driver, _spec)
}

func (crq *CommentReportQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(commentreport.Table, commentreport.Columns, sqlgraph.NewFieldSpec(commentreport.FieldID, field.TypeInt))
	_spec.From = crq.sql
	if unique := crq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if crq.path != nil {
		_spec.Unique = true
	}
	if fields := crq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, commentreport.FieldID)
		for i := range fields {
			if fields[i] != commentreport.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if crq.withUser != nil {
			_spec.Node.AddColumnOnce(commentreport.FieldReporterID)
		}
		if crq.withComment != nil {
			_spec.Node.AddColumnOnce(commentreport.FieldCommentID)
		}
		if crq.withReportType != nil {
			_spec.Node.AddColumnOnce(commentreport.FieldReportTypeID)
		}
	}
	if ps := crq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := crq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := crq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := crq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (crq *CommentReportQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(crq.driver.Dialect())
	t1 := builder.Table(commentreport.Table)
	columns := crq.ctx.Fields
	if len(columns) == 0 {
		columns = commentreport.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if crq.sql != nil {
		selector = crq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if crq.ctx.Unique != nil && *crq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range crq.predicates {
		p(selector)
	}
	for _, p := range crq.order {
		p(selector)
	}
	if offset := crq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := crq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CommentReportGroupBy is the group-by builder for CommentReport entities.
type CommentReportGroupBy struct {
	selector
	build *CommentReportQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (crgb *CommentReportGroupBy) Aggregate(fns ...AggregateFunc) *CommentReportGroupBy {
	crgb.fns = append(crgb.fns, fns...)
	return crgb
}

// Scan applies the selector query and scans the result into the given value.
func (crgb *CommentReportGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, crgb.build.ctx, "GroupBy")
	if err := crgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CommentReportQuery, *CommentReportGroupBy](ctx, crgb.build, crgb, crgb.build.inters, v)
}

func (crgb *CommentReportGroupBy) sqlScan(ctx context.Context, root *CommentReportQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(crgb.fns))
	for _, fn := range crgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*crgb.flds)+len(crgb.fns))
		for _, f := range *crgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*crgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := crgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CommentReportSelect is the builder for selecting fields of CommentReport entities.
type CommentReportSelect struct {
	*CommentReportQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (crs *CommentReportSelect) Aggregate(fns ...AggregateFunc) *CommentReportSelect {
	crs.fns = append(crs.fns, fns...)
	return crs
}

// Scan applies the selector query and scans the result into the given value.
func (crs *CommentReportSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, crs.ctx, "Select")
	if err := crs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CommentReportQuery, *CommentReportSelect](ctx, crs.CommentReportQuery, crs, crs.inters, v)
}

func (crs *CommentReportSelect) sqlScan(ctx context.Context, root *CommentReportQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(crs.fns))
	for _, fn := range crs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*crs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := crs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
