// Code generated by ent, DO NOT EDIT.

package reporttype

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/leeeeeoy/go_study/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ReportType {
	return predicate.ReportType(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ReportType {
	return predicate.ReportType(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ReportType {
	return predicate.ReportType(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ReportType {
	return predicate.ReportType(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ReportType {
	return predicate.ReportType(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ReportType {
	return predicate.ReportType(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ReportType {
	return predicate.ReportType(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ReportType {
	return predicate.ReportType(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ReportType {
	return predicate.ReportType(sql.FieldLTE(FieldID, id))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ReportType {
	return predicate.ReportType(sql.FieldEQ(FieldDescription, v))
}

// InActive applies equality check predicate on the "in_active" field. It's identical to InActiveEQ.
func InActive(v bool) predicate.ReportType {
	return predicate.ReportType(sql.FieldEQ(FieldInActive, v))
}

// OrderNum applies equality check predicate on the "order_num" field. It's identical to OrderNumEQ.
func OrderNum(v int) predicate.ReportType {
	return predicate.ReportType(sql.FieldEQ(FieldOrderNum, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ReportType {
	return predicate.ReportType(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ReportType {
	return predicate.ReportType(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ReportType {
	return predicate.ReportType(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ReportType {
	return predicate.ReportType(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ReportType {
	return predicate.ReportType(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ReportType {
	return predicate.ReportType(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ReportType {
	return predicate.ReportType(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ReportType {
	return predicate.ReportType(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ReportType {
	return predicate.ReportType(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ReportType {
	return predicate.ReportType(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ReportType {
	return predicate.ReportType(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.ReportType {
	return predicate.ReportType(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.ReportType {
	return predicate.ReportType(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ReportType {
	return predicate.ReportType(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ReportType {
	return predicate.ReportType(sql.FieldContainsFold(FieldDescription, v))
}

// InActiveEQ applies the EQ predicate on the "in_active" field.
func InActiveEQ(v bool) predicate.ReportType {
	return predicate.ReportType(sql.FieldEQ(FieldInActive, v))
}

// InActiveNEQ applies the NEQ predicate on the "in_active" field.
func InActiveNEQ(v bool) predicate.ReportType {
	return predicate.ReportType(sql.FieldNEQ(FieldInActive, v))
}

// OrderNumEQ applies the EQ predicate on the "order_num" field.
func OrderNumEQ(v int) predicate.ReportType {
	return predicate.ReportType(sql.FieldEQ(FieldOrderNum, v))
}

// OrderNumNEQ applies the NEQ predicate on the "order_num" field.
func OrderNumNEQ(v int) predicate.ReportType {
	return predicate.ReportType(sql.FieldNEQ(FieldOrderNum, v))
}

// OrderNumIn applies the In predicate on the "order_num" field.
func OrderNumIn(vs ...int) predicate.ReportType {
	return predicate.ReportType(sql.FieldIn(FieldOrderNum, vs...))
}

// OrderNumNotIn applies the NotIn predicate on the "order_num" field.
func OrderNumNotIn(vs ...int) predicate.ReportType {
	return predicate.ReportType(sql.FieldNotIn(FieldOrderNum, vs...))
}

// OrderNumGT applies the GT predicate on the "order_num" field.
func OrderNumGT(v int) predicate.ReportType {
	return predicate.ReportType(sql.FieldGT(FieldOrderNum, v))
}

// OrderNumGTE applies the GTE predicate on the "order_num" field.
func OrderNumGTE(v int) predicate.ReportType {
	return predicate.ReportType(sql.FieldGTE(FieldOrderNum, v))
}

// OrderNumLT applies the LT predicate on the "order_num" field.
func OrderNumLT(v int) predicate.ReportType {
	return predicate.ReportType(sql.FieldLT(FieldOrderNum, v))
}

// OrderNumLTE applies the LTE predicate on the "order_num" field.
func OrderNumLTE(v int) predicate.ReportType {
	return predicate.ReportType(sql.FieldLTE(FieldOrderNum, v))
}

// HasCommentReport applies the HasEdge predicate on the "comment_report" edge.
func HasCommentReport() predicate.ReportType {
	return predicate.ReportType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, CommentReportTable, CommentReportColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommentReportWith applies the HasEdge predicate on the "comment_report" edge with a given conditions (other predicates).
func HasCommentReportWith(preds ...predicate.CommentReport) predicate.ReportType {
	return predicate.ReportType(func(s *sql.Selector) {
		step := newCommentReportStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBoardReport applies the HasEdge predicate on the "board_report" edge.
func HasBoardReport() predicate.ReportType {
	return predicate.ReportType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, BoardReportTable, BoardReportColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBoardReportWith applies the HasEdge predicate on the "board_report" edge with a given conditions (other predicates).
func HasBoardReportWith(preds ...predicate.BoardReport) predicate.ReportType {
	return predicate.ReportType(func(s *sql.Selector) {
		step := newBoardReportStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReportType) predicate.ReportType {
	return predicate.ReportType(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReportType) predicate.ReportType {
	return predicate.ReportType(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReportType) predicate.ReportType {
	return predicate.ReportType(func(s *sql.Selector) {
		p(s.Not())
	})
}
