// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Board is the predicate function for board builders.
type Board func(*sql.Selector)

// BoardHashtag is the predicate function for boardhashtag builders.
type BoardHashtag func(*sql.Selector)

// BoardLike is the predicate function for boardlike builders.
type BoardLike func(*sql.Selector)

// BoardReport is the predicate function for boardreport builders.
type BoardReport func(*sql.Selector)

// BookMark is the predicate function for bookmark builders.
type BookMark func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// CommentLike is the predicate function for commentlike builders.
type CommentLike func(*sql.Selector)

// CommentMention is the predicate function for commentmention builders.
type CommentMention func(*sql.Selector)

// CommentReport is the predicate function for commentreport builders.
type CommentReport func(*sql.Selector)

// Hashtag is the predicate function for hashtag builders.
type Hashtag func(*sql.Selector)

// ReportType is the predicate function for reporttype builders.
type ReportType func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
